services:
  web:
    build:
      context: .
    ports:
      - 8000:8000
    environment:
      - SQL_ALCHEMY_URL=
      - SECRET_KEY=
      - ALGORITHM=
      - ACCESS_TOKEN_EXPIRE_IN=
    volumes:
      - .:/app
      - /app/.venv
    